# Generated by Django 3.2.6 on 2021-08-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_rename_to_do_list_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=10000),
        ),
    ]
