# Generated by Django 3.2.6 on 2021-08-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', 'id']},
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(null=True, to='tasks.Tag'),
        ),
    ]
