# Generated by Django 3.2.6 on 2021-08-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
