# Generated by Django 3.2.6 on 2021-08-31 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='show',
            new_name='show_task',
        ),
    ]
