# Generated by Django 3.2.6 on 2021-09-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_group_task_group_selected'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Folder',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='group_selected',
            new_name='folder_selected',
        ),
    ]
