# Generated by Django 3.2.6 on 2021-09-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_task_folder_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
